config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/signup", to: "registers#new", as: "signup"
  post "/signup", to: "registers#create"

  get "/signin", to: "sessions#new", as: "session"
  post "/signin", to: "sessions#create"

  delete "/signout", to: "sessions#destroy"

  namespace :admin do
    resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy 
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  enum status: %i(wait_confirm delivering completed canceled)
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items, dependent: :destroy

  enum status: %i(enabled disabled)
end

app/models/user.rb
class User < ApplicationRecord  
  has_secure_password

  has_many :orders, dependent: :destroy
  has_many :order_items, through: :orders

  validates :name, presence: true, length: { maximum: Settings.user.validates.name.max }
  validates :email, presence: true, format: { with: Settings.regex.email }
  validates :password, presence: true, length: { minimum: Settings.user.validates.password.min }, on: :create
  validates :password_confirmation, presence: true, on: :create

  enum role: %i(user admin)
  enum status: %i(enabled disabled)
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index; end
  def create; end
  def new; end
  def edit; end
  def show; end
  def update; end
  def destroy; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= session[:remember_token] && User.find_by_remember_token(session[:remember_token])
  end

  def redirect_back_or(default)
    redirect_to session[:return_to] || default
    session.delete(:return_to)
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end
end

app/controllers/concerns/sessions_action.rb
module SessionsAction 
  extend ActiveSupport::Concern

  def sign_in(user)
    user.update(remember_token: SecureRandom.urlsafe_base64)
    session[:remember_token] = user.remember_token
  end

  def sign_out
    current_user.update(remember_token: nil)
    session[:remember_token] = nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  include SessionsAction

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = t("sign_up.create_success")
      redirect_to root_path
    else
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsAction

  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      sign_in user
      flash[:success] = t("sign_in.success_message")
      redirect_back_or root_path
    else
      flash.now[:error] = t("sign_in.error_message")
      render :new
    end
  end

  def destroy
    sign_out
    flash[:notice] = t("sign_out.success_message")
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = t("base_title")
    page_title.empty? ? base_title : "#{base_title} | #{page_title}"
  end

  def alert_class_for(flash_type)
    case flash_type.to_sym
    when :success
      "alert-success"
    when :error, :alert
      "alert-danger"
    when :warning, :notice
      "alert-warning"
    when :info
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/views/admin/products/index.html.erb
  <div class="container mt-4">
    <h2>List of Products</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>Status</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Product 1</td>
          <td>$100</td>
          <td>
            <div class="form-check form-switch">
              <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
              <label class="form-check-label" for="flexSwitchCheckDefault">Default switch checkbox input</label>
            </div>
          </td>
          <td>
            <button class="btn btn-primary">Edit</button>
            <button class="btn btn-primary custom-">Delete</button>
          </td>
        </tr>
      </tbody>
    </table>
    <h2>Create New Product</h2>
    <form>
      <div class="mb-3">
        <label for="name" class="form-label">Name:</label>
        <input type="text" class="form-control" id="name" placeholder="Enter product name">
      </div>

      <div class="mb-3">
        <label for="description" class="form-label">Description:</label>
        <textarea class="form-control" id="description" rows="3" placeholder="Enter product description"></textarea>
      </div>

      <div class="mb-3">
        <label for="price" class="form-label">Price:</label>
        <input type="number" class="form-control" id="price" placeholder="Enter product price">
      </div>

      <div class="mb-3">
        <label for="image" class="form-label">Upload Image:</label>
        <input type="file" class="form-control" id="image">
      </div>

      <div class="mb-3">
        <label for="category" class="form-label">Product Category:</label>
        <select class="form-select" id="category">
          <option value="1">Electronics</option>
          <option value="2">Clothing</option>
          <option value="3">Home & Living</option>
        </select>
      </div>

      <div class="mb-3">
        <label for="sold" class="form-label">Number Sold:</label>
        <input type="number" class="form-control" id="sold" placeholder="Enter number of products sold">
      </div>

      <button type="submit" class="btn btn-primary">Create Product</button>
    </form>
  </div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/indexx.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">
      <%= render "shared/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/registers/new.html.erb
<% provide(:title, t("sign_up.title"))%>
<h1><%= t("sign_up.title") %></h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_with(model: @user, url: signup_path) do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <div class="mb-3">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :email, class: "form-label" %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :password, class: "form-label" %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= f.label :password_confirmation, class: "form-label" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </div>
      <%= f.submit t("sign_up.title"), class: "btn btn-large btn-primary custom-btn-primary" %>
    <% end %>
    <p class="mt-3 text-center">Already have an account? <%= link_to t("sign_in_now"), session_path %></p>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger" role="alert">
      <%= t("count_errors", errors: pluralize(object.errors.count, "error")) %>.
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert <%= alert_class_for(flash_type) %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<% if current_user&.admin? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#">Admin Dashboard</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebar" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle sidebar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="sidebar">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Order</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">User</a>
          </li>
        </ul>
        <div class="navbar-collapse justify-content-end">
          <div class="btn-group">
            <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </button>
            <ul class="dropdown-menu">
              <li><%= button_to t("sign_out.title"), signout_path, method: "delete", class: "dropdown-item" %></li>
            </ul>
          </div>
      </div>
      </div>
    </div>
  </nav>
<% else %>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <%= link_to t("base_title"), root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#">Cart</a>
          </li>
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Options
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li><a class="dropdown-item" href="#">Order History</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= button_to t("sign_out.title"), signout_path, method: "delete", class: "dropdown-item" %></li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to t("sign_in.title"), session_path, class: "nav-link" %>
            </li>        
          <% end %>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
<% end %>